name: example 

on: push

jobs:
        job_1:
                runs-on: ubuntu-latest
                steps:
                        - name: My first 
                          run: echo This is the first step
